In [1]:
import numpy as np

In [2]:
#Define Independent and dependent variables. Where X is the independent variable and Y is a dependent variable
X=np.array([[0,1],[35424,1], [73440,1], [109728,1], [136512,1] ,[176256,1]])
Y=np.array([87345,244555,213087,222042,326125,434130])

print(X)
print(Y)

[[     0      1]
 [ 35424      1]
 [ 73440      1]
 [109728      1]
 [136512      1]
 [176256      1]]
[ 87345 244555 213087 222042 326125 434130]


In [3]:
X_trans = np.transpose(X)
print(X_trans)

[[     0  35424  73440 109728 136512 176256]
 [     1      1      1      1      1      1]]


<h1><center>$X^{T}\cdot X$</center></h1>

In [4]:
X_T_into_X = np.matmul(np.transpose(X),X)
print(X_T_into_X)

[[-329245696     531360]
 [    531360          6]]


<h1><center>$\left ( X^{T}\cdot X \right )^{-1}$</center></h1>

In [5]:
X_trans_X_inverse = np.linalg.inv(X_T_into_X)

print(X_trans_X_inverse)

[[-2.11030624e-11  1.86888721e-06]
 [ 1.86888721e-06  1.15801541e-03]]


<h1><center>$X^{T}\cdot Y$</center></h1>

In [6]:
X_trans_into_Y = np.matmul(np.transpose(X),Y)

print(X_trans_into_Y)

[-2084248384     1527284]


<h1><center>$\left ( X^{T}\cdot X \right )^{-1}X^{T}\cdot Y$</center></h1>

In [7]:
A = np.matmul(X_trans_X_inverse,X_trans_into_Y) #w1 and w0
print(A)

[    2.89830556 -2126.60673346]


In [8]:
#Prediction for the new X.
w1 = A [0]
w0 = A [1]

x = 1591 #insert values needed

#g = w0 + w1 * x_new


dist_Berlin = 440
dist_Moscow = 2040
dist_Kyiv = 1591

g_Berlin = w0 + w1 * dist_Berlin
g_Moscow = w0 + w1 * dist_Moscow
g_Kyiv = w0 + w1 * dist_Kyiv

print(g_Berlin)
print(g_Moscow)
print(g_Kyiv)

-851.3522886852197
3785.9366014104407
2484.5974066273457
