In [13]:
import numpy as np

In [14]:
#Define Independent and dependent variables. Where X is the independent variable and Y is a dependent variable
X=np.array([[0,1],[35424,1], [73440,1], [109728,1], [136512,1] ,[176256,1]])
Y=np.array([87345,244555,213087,222042,326125,434130])

print(X)
print(Y)

[[     0      1]
 [ 35424      1]
 [ 73440      1]
 [109728      1]
 [136512      1]
 [176256      1]]
[ 87345 244555 213087 222042 326125 434130]


In [15]:
X_trans = np.transpose(X)
print(X_trans)

[[     0  35424  73440 109728 136512 176256]
 [     1      1      1      1      1      1]]


<h1><center>$X^{T}\cdot X$</center></h1>

In [16]:
X_T_into_X = np.matmul(np.transpose(X),X)
print(X_T_into_X)

[[-329245696     531360]
 [    531360          6]]


<h1><center>$\left ( X^{T}\cdot X \right )^{-1}$</center></h1>

In [17]:
X_trans_X_inverse = np.linalg.inv(X_T_into_X)

print(X_trans_X_inverse)

[[-2.11030624e-11  1.86888721e-06]
 [ 1.86888721e-06  1.15801541e-03]]


<h1><center>$X^{T}\cdot Y$</center></h1>

In [18]:
X_trans_into_Y = np.matmul(np.transpose(X),Y)

print(X_trans_into_Y)

[-2084248384     1527284]


<h1><center>$\left ( X^{T}\cdot X \right )^{-1}X^{T}\cdot Y$</center></h1>

In [19]:
A = np.matmul(X_trans_X_inverse,X_trans_into_Y) #w1 and w0
print(A)

[    2.89830556 -2126.60673346]


In [20]:
#Prediction for the new X.
w1 = A [0]
w0 = A [1]

#insert values needed

#g = w0 + w1 * x_new


dist_Berlin = 440
dist_Moscow = 2040
dist_Kyiv = 1591

g_Berlin = w0 + w1 * dist_Berlin
g_Moscow = w0 + w1 * dist_Moscow
g_Kyiv = w0 + w1 * dist_Kyiv

print(g_Berlin)
print(g_Moscow)
print(g_Kyiv)

-851.3522886852197
3785.9366014104407
2484.5974066273457


In [23]:
Y_predict = []
for i in X:
    pred = w0 + w1 * i[0]
    Y_predict.append(pred)
print(Y_predict)

[-2126.6067334615263, 100542.96929325639, 210724.9533219293, 315898.66534929886, 393526.8813695002, 508717.13739947637]


In [33]:
#Mean squared error on training data
n=len(X)
Error = 0
for i in range (6):
    E = (Y[i]-Y_predict[i])**2
    Error = E+Error

MSE = (1/n)*Error
MSE

7944256828.723909

In [34]:
X = [0,35424,73440,109728,136512,176256]
Y = [87345,244555,213087,222042,326125,434130]

In [35]:
X_avg = np.average(X)

In [36]:
X_max = np.max(X)

In [37]:
X_min = np.min(X)

In [38]:
X_norm = (X-X_min)/(X_max-X_min)

In [39]:
X_norm

array([0.        , 0.20098039, 0.41666667, 0.62254902, 0.7745098 ,
       1.        ])

In [40]:
Y_norm = (Y-np.min(Y))/(np.max(Y)-np.min(Y))

In [41]:
Y_norm

array([0.        , 0.45333564, 0.36259354, 0.38841645, 0.68855343,
       1.        ])